### ISSUE TITLE
Consider using React Proxy

### ISSUE THREAD

**Issue by gaearon** [Kureev/browserify-react-live#10]
[React Proxy](https://github.com/gaearon/react-proxy) is still in early stages but it's considerably more stable than React Hot API and will eventually replace it.

Some advantages of React Proxy:
- Fully covered by tests
- Doesn't need `ReactMount`
- Supports ES6 getters and setters
- Supports hot-reloading static methods

I have not actually tested it on RHL yet, but feel free to investigate it in parallel with me.
I'll port React Hot API to use it internally within a few days, but I'd just suggest using it directly.

**Comment by gaearon** [comment]
Whoops, I forgot I renamed it lol. React Proxy it is.

**Comment by Kureev** [comment]
Wow, thanks for the hint, will take a look now

**Comment by Kureev** [comment]
Implemented in `3.0.0`
