### ISSUE TITLE
Issue working with babelify

### ISSUE THREAD

**Issue by Webkadabra** [Kureev/browserify-react-live#11]
If I add "babelify" to transform (via package of CLI options) I get error:

```
Error: Parsing file D:\WebServers\custom_home\_BFK_NODE\_Strongloop\browserify-r
eact-live\examples\basic\client\users\store.js: Bad character escape sequence (8
:81)
```

Apparently there is nothing bad with store.js since error goes away if I remove 'browserify-react-live' transform. 

However, my `store.js`:

``` javascript
import User from './user';
import {Record} from 'immutable';
import {actions as authActions} from '../auth/actions';

function revive(state) {
  // Handle case user was authenticated on the server.
  const viewer = state && state.get('viewer');
  return new (Record({
    viewer: viewer ? new User(viewer) : null
  }));
}

export default function(state, action, payload) {
  if (!action) state = revive(state);

  switch (action) {

  case authActions.loginSuccess:
    // Hideous side effect hack, will be removed soon with new react-router.
    User.isLoggedIn = true;
      console.log('Set viewer to:',payload)
    return state.set('viewer', new User(payload));

  }

  return state;
}
```

I'm sorry if this is a bad question - I'm kind of new in Node. 

My CLI command is:

``` bash
watchify -t [babelify --stage 0] -t browserify-react-live client/main.js -o dist/build.js
```

Please, advice.

**Comment by Kureev** [comment]
Hm, that's really strange. I would appreciate if you can share your code to let me take a look on it.

**Comment by Webkadabra** [comment]
@Kureev I'm simply trying to make it work with client/server from https://github.com/este/este
Looks like there is a conflict going on with babel and react-live: if I add readt-live transform, then whatever it does to code (some require() constructions, I think?) can not be parsen by babel with --stage=0; If I remove babel, then my es6/ code can not be compiled also. 

I'm now trying to make it work with some Gulp scripts - I will definitely share if I will work something out, but I'm a bit desperate :)

**Comment by Webkadabra** [comment]
@Kureev can you please show how should I require browserify-react-live patch server so I can run it from Gulp?

**Comment by Webkadabra** [comment]
@Kureev Actually, here is how I'm doing it - I'm new to node, but looks like it's ok:

```
var runServer = require('browserify-patch-server')
gulp.task('patchServer', function() {
 runServer(['./scripts/components/*.jsx'], {
        port: 8081
    });
});
```

**Comment by Webkadabra** [comment]
@Kureev I kind of managed to make it work with Gulp, but whenever client files are updated, browserify-patch-server is throwing error:

```
[BS] Serving files from: ./
[21:26:39] Finished 'watchify' after 6.08 s
ℹ [BDS:SYSTEM] [21:26:50] File scripts/components/mycomponent.jsx has been changed
D:\WebServers\custom_home\_BFK_NODE\_Strongloop\react-starterify\node_modules\browserify-patch-server\makePatch.js:9
    })[0].content;
         ^
TypeError: Cannot read property 'content' of undefined
    at calculateDiff (D:\WebServers\custom_home\_BFK_NODE\_Strongloop\react-starterify\node_modules\browserify-patch-server\makePatch.js:9:10)
    at composeWrapper (D:\WebServers\custom_home\_BFK_NODE\_Strongloop\react-starterify\node_modules\browserify-patch-server\compose.js:6:24)
    at processFile (D:\WebServers\custom_home\_BFK_NODE\_Strongloop\react-starterify\node_modules\browserify-patch-server\index.js:119:50)
    at D:\WebServers\custom_home\_BFK_NODE\_Strongloop\react-starterify\node_modules\babel\node_modules\babel-core\lib\api\node.js:125:5
    at fs.js:334:14
    at D:\WebServers\custom_home\_BFK_NODE\_Strongloop\react-starterify\node_modules\browserify-patch-server\node_modules\chokidar\node_modules\readdi
rp\node_modules\graceful-fs\graceful-fs.js:42:10
    at D:\WebServers\custom_home\_BFK_NODE\_Strongloop\react-starterify\node_modules\gulp-image\node_modules\temp-write\node_modules\graceful-fs\grace
ful-fs.js:42:10
    at D:\WebServers\custom_home\_BFK_NODE\_Strongloop\react-starterify\node_modules\watchify\node_modules\chokidar\node_modules\readdirp\node_modules
\graceful-fs\graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Am I in too deep? ^^

**Comment by Kureev** [comment]
Hm, I haven't tried to run babel with `--stage 0`, but all my examples runs with babel. Let me take a look...

**Comment by Kureev** [comment]
> I kind of managed to make it work with Gulp, but whenever client files are updated, browserify-patch-server is throwing error...

Seems error with paths on windows. If you have a time to help me with it, I'd like to debug it with you by skype or smth... (in this case write me a mail, I'll send you my skype)

**Comment by Webkadabra** [comment]
@Kureev you were right - I changed gulp's patchServer task to:

```
runServer(['scripts/components/mycomponent.jsx'], {
        port: 8081
    });
```

Now server successfully sees changes and sends diff to client. On client side, however, there is still problem with paths: mycomponent.jst has line:

> import packageJSON from '../../package.json';

It works well for initial run, but when patch server tries to read it, we have error (when patch is sent to client, error is on client, not server):

```
[21:47:29] Patch for scripts/components/mycomponent.jsx (0.35kb)
app.js:5505 - 'God'
app.js:5503 + 'Go'
app.js:1 Uncaught Error: Cannot find module '../../package.json'
```

Thank you for communication! I would love to try to debug it, my Skype is `thorn_ua`

**Comment by Kureev** [comment]
Should I still keep it opened?
