### ISSUE TITLE
import react addons error

### ISSUE THREAD

**Issue by fraserxu** [Kureev/browserify-react-live#4]
I'm trying to play with the basic example, when I try to import the react with addons like this

``` JavaScript
'use strict';

import React from 'react/addons';

console.log('React', React);

const styles = {
  button: {
    padding: 20,
    display: 'block',
  },
};

module.exports = class MyComponent extends React.Component //...

```

React is actually undefined here and I got the `Uncaught TypeError: Cannot read property 'Component' of undefined` error.

Note that this work if without the `browserify-react-live` transformer.

**Comment by Kureev** [comment]
Can you double check you're using `1.0.1` version, please?

**Comment by fraserxu** [comment]
I'm using `1.0.0` at the moment, let me try `1.0.1` right now.

**Comment by fraserxu** [comment]
It works now after upgrade to `v1.0.1`, thanks a lot!
